### ISSUE TITLE
http API test support

### ISSUE THREAD

**Issue by WeihanLi** [WeihanLi/dotnet-httpie#79]
### Testing spec

- environment
- collection(request collection)
- group(request group in a collection)
- request(specific request)
- variable

```yaml
collectionName: testCollection
  variables:
    - name: value

  - groupName: testGroup
      variables:
        - name: value
      - requestName: hello request
        variables:
          - name: value      
        assertion: "$response.EnsureSuccessStatusCode()"
```
